<!DOCTYPE html>
<html>
<head>
    <title>Calendar HTML Debug Output</title>
    <style>
        body {
            font-family: monospace;
            padding: 20px;
            background: #f5f5f5;
        }
        .debug-section {
            background: white;
            padding: 20px;
            margin: 20px 0;
            border: 2px solid #333;
            border-radius: 8px;
        }
        h2 {
            color: #d32f2f;
            margin-top: 0;
        }
        pre {
            background: #263238;
            color: #aed581;
            padding: 15px;
            border-radius: 4px;
            overflow-x: auto;
        }
        .highlight {
            background: yellow;
            color: black;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>🔍 Calendar Plugin HTML Debug Output</h1>
    
    <div class="debug-section">
        <h2>Generated Event Dialog HTML</h2>
        <p>This is the actual HTML that should be generated by the plugin:</p>
        <pre><?php
// Simulate what the plugin generates
$calId = 'test_cal_123';
$namespace = 'test';

$html = '<div class="event-dialog-compact" id="dialog-' . $calId . '" style="display:none;">';
$html .= '<div class="dialog-overlay" onclick="closeEventDialog(\'' . $calId . '\')"></div>';
$html .= '<div class="dialog-content-compact">';

// Title
$html .= '<h4 id="dialog-title-' . $calId . '">Add Event</h4>';

// Form start
$html .= '<form id="eventform-' . $calId . '" onsubmit="saveEventCompact(\'' . $calId . '\', \'' . $namespace . '\'); return false;">';

// Hidden event ID
$html .= '<input type="hidden" id="event-id-' . $calId . '" name="eventId" value="">';

// DATE FIELD - Making it absolutely clear
$html .= '<div class="form-row" style="background:#fff3cd;padding:12px;border:3px solid #ff9800;border-radius:6px;margin-bottom:15px;">';
$html .= '<label style="color:#ff6f00;font-weight:bold;font-size:14px;margin-bottom:8px;display:block;">📅 EVENT DATE (Required)</label>';
$html .= '<input type="date" ';
$html .= 'id="event-date-' . $calId . '" ';
$html .= 'name="date" ';
$html .= 'required ';
$html .= 'class="date-input-field" ';
$html .= 'style="width:100%;padding:12px;font-size:16px;border:2px solid #ff9800;border-radius:4px;background:white;" ';
$html .= 'value="' . date('Y-m-d') . '">';
$html .= '</div>';

// Title field
$html .= '<div class="form-row">';
$html .= '<label>Event Title</label>';
$html .= '<input type="text" id="event-title-' . $calId . '" name="title" required placeholder="Enter event title">';
$html .= '</div>';

// Time field
$html .= '<div class="form-row">';
$html .= '<label>Time (optional)</label>';
$html .= '<input type="time" id="event-time-' . $calId . '" name="time" placeholder="HH:MM">';
$html .= '</div>';

// Color field
$html .= '<div class="form-row">';
$html .= '<label>Color</label>';
$html .= '<input type="color" id="event-color-' . $calId . '" name="color" value="#3498db">';
$html .= '</div>';

// Description field
$html .= '<div class="form-row">';
$html .= '<label>Description (optional)</label>';
$html .= '<textarea id="event-desc-' . $calId . '" name="description" rows="3" placeholder="Add event details..."></textarea>';
$html .= '</div>';

// Action buttons
$html .= '<div class="dialog-actions">';
$html .= '<button type="submit" class="btn-save">Save Event</button>';
$html .= '<button type="button" class="btn-cancel" onclick="closeEventDialog(\'' . $calId . '\')">Cancel</button>';
$html .= '</div>';

$html .= '</form>';
$html .= '</div></div>';

// Highlight the date field in the output
$highlighted = str_replace(
    'type="date"',
    '<span class="highlight">type="date"</span>',
    htmlspecialchars($html)
);

echo $highlighted;
?></pre>
    </div>

    <div class="debug-section">
        <h2>Search for Date Field</h2>
        <p>Looking for the date input in the HTML above...</p>
        <pre><?php
if (strpos($html, 'type="date"') !== false) {
    echo "✅ SUCCESS: Date field found in HTML!\n\n";
    echo "ID: event-date-" . $calId . "\n";
    echo "Type: date\n";
    echo "Required: yes\n";
    echo "Default value: " . date('Y-m-d') . "\n";
} else {
    echo "❌ ERROR: Date field NOT found in HTML!\n";
}
?></pre>
    </div>

    <div class="debug-section">
        <h2>Rendered Preview (How it should look)</h2>
        <div style="max-width: 400px; margin: 20px auto;">
            <?php echo $html; ?>
            <style>
                .event-dialog-compact {
                    display: block !important;
                    position: relative;
                }
                .dialog-overlay {
                    display: none;
                }
                .dialog-content-compact {
                    background: white;
                    padding: 20px;
                    border-radius: 8px;
                    box-shadow: 0 4px 12px rgba(0,0,0,0.2);
                }
                .form-row {
                    margin-bottom: 14px;
                }
                .form-row label {
                    display: block;
                    font-size: 12px;
                    font-weight: 600;
                    color: #555;
                    margin-bottom: 4px;
                }
                .form-row input[type="text"],
                .form-row input[type="time"],
                .form-row input[type="date"],
                .form-row input[type="color"],
                .form-row textarea {
                    width: 100%;
                    padding: 8px;
                    border: 1px solid #d0d0d0;
                    border-radius: 4px;
                    font-size: 13px;
                    box-sizing: border-box;
                }
                .dialog-actions {
                    display: flex;
                    gap: 8px;
                    margin-top: 16px;
                }
                .btn-save, .btn-cancel {
                    padding: 8px 16px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                }
                .btn-save {
                    background: #4caf50;
                    color: white;
                }
                .btn-cancel {
                    background: #95a5a6;
                    color: white;
                }
            </style>
        </div>
    </div>

    <div class="debug-section">
        <h2>JavaScript Test</h2>
        <button onclick="testDateField()">Test Date Field Access</button>
        <pre id="js-result"></pre>
        <script>
            function testDateField() {
                const calId = 'test_cal_123';
                const dateField = document.getElementById('event-date-' + calId);
                
                let output = '';
                output += 'Searching for: event-date-' + calId + '\n\n';
                
                if (dateField) {
                    output += '✅ Date field FOUND!\n\n';
                    output += 'Element: ' + dateField.tagName + '\n';
                    output += 'Type: ' + dateField.type + '\n';
                    output += 'ID: ' + dateField.id + '\n';
                    output += 'Name: ' + dateField.name + '\n';
                    output += 'Required: ' + dateField.required + '\n';
                    output += 'Value: ' + dateField.value + '\n';
                    output += 'Visible: ' + (dateField.offsetParent !== null) + '\n';
                    output += 'Readonly: ' + dateField.readOnly + '\n';
                    output += 'Disabled: ' + dateField.disabled + '\n';
                } else {
                    output += '❌ Date field NOT FOUND!\n';
                    output += 'This means JavaScript cannot access it.\n';
                }
                
                document.getElementById('js-result').textContent = output;
            }
        </script>
    </div>

    <div class="debug-section">
        <h2>What to Check in Your DokuWiki</h2>
        <ol>
            <li>View page source (Ctrl+U) of your calendar page</li>
            <li>Search for: <code>event-date-</code></li>
            <li>You should find: <code>&lt;input type="date" id="event-date-cal_..."&gt;</code></li>
            <li>If found: Plugin is working correctly</li>
            <li>If NOT found: Plugin files not uploaded or cached version</li>
        </ol>
        <p><strong>If the date field is in the HTML but not visible:</strong></p>
        <ul>
            <li>Check for CSS that might be hiding it</li>
            <li>Check if form is display:none</li>
            <li>Open browser dev tools (F12) and inspect the dialog</li>
        </ul>
    </div>
</body>
</html>
